name: Deploy Node.js App

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
<<<<<<< HEAD
    - name: Checkout code
      uses: actions/checkout@v3

=======
    # 1️⃣ Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2️⃣ Configure AWS credentials
>>>>>>> d440ded1df63541a0eaba412cbe6d52b78e1d6dd
    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

<<<<<<< HEAD
=======
    # 3️⃣ Login to ECR
>>>>>>> d440ded1df63541a0eaba412cbe6d52b78e1d6dd
    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

<<<<<<< HEAD
=======
    # 4️⃣ Build Docker image
>>>>>>> d440ded1df63541a0eaba412cbe6d52b78e1d6dd
    - name: Build Docker image
      run: |
        IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/nodeapp:latest"
        docker build -t $IMAGE_URI .
        docker push $IMAGE_URI

<<<<<<< HEAD
=======
    # 5️⃣ SSH into EC2 and deploy
>>>>>>> d440ded1df63541a0eaba412cbe6d52b78e1d6dd
    - name: Deploy on EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_PUBLIC_IP }}
<<<<<<< HEAD
        username: ec2-user
=======
        username: ubuntu
>>>>>>> d440ded1df63541a0eaba412cbe6d52b78e1d6dd
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull ${{ steps.login-ecr.outputs.registry }}/nodeapp:latest
          docker stop nodeapp || true
          docker rm nodeapp || true
          docker run -d -p 3000:3000 --name nodeapp ${{ steps.login-ecr.outputs.registry }}/nodeapp:latest
